### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Kaaveh** [riggaroo/compose-playtime#9]
Hey Rebecca
You have a video on Android developers Youtube channel titled [Introduction to drawing in Compose](https://www.youtube.com/watch?v=1yiuxWK74vI). After renaming a file named `WeTradeGraph.kt` the GitHub link in the description of the video broke.
I just wanted to let you know.

**Comment by riggaroo** [comment]
Thanks for the report, its now fixed.
